# -*- coding: utf-8 -*-
"""MoE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/103aFWkzp1XF_8077tgqfVha0fcnfopRH
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import seaborn as sns

# Uncomment this for reproducibility
# torch.manual_seed(42)
# np.random.seed(42)

n_classes = 10
#n_samples = 1200
n_experts = 4
top_k = 2
hidden_dim = 256
epochs = 20
lr = 1e-3
load_balancing_coeff = 0.01
in_dim = 784
# x_np, y_np = make_blobs(n_samples=n_samples, centers=n_classes, cluster_std=0.9, random_state = 42)
# x_np = StandardScaler().fit_transform(x_np)

transform = transforms.Compose([transforms.ToTensor(), transforms.Lambda(lambda x: x.view(-1))])
train_data = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
loader = torch.utils.data.DataLoader(train_data, batch_size=256, shuffle=True)

# x = torch.tensor(x_np, dtype=torch.float32)
# y = torch.tensor(y_np, dtype=torch.long)

class Expert(nn.Module):
  """2 layer MLP"""
  def __init__(self, in_dim, hidden_dim, out_dim):
    super().__init__()
    self.net = nn.Sequential(nn.Linear(in_dim, hidden_dim), nn.ReLU(), nn.Linear(hidden_dim, out_dim),)

  def forward(self, x):
    return self.net(x)


class GatingNetwork(nn.Module):
  """prob dist over experts for each input"""
  def __init__(self, in_dim, n_experts):
    super().__init__()
    self.fc = nn.Linear(in_dim, n_experts)

  def forward(self, x, top_k):
    logits = self.fc(x)
    gates = F.softmax(logits, dim=-1)

    top_k_vals, top_k_idx = torch.topk(gates, top_k, dim=-1)

    sparse_gates = torch.zeros_like(gates)
    sparse_gates.scatter_(1, top_k_idx, top_k_vals)

    #normalize
    sparse_gates = sparse_gates/(sparse_gates.sum(-1, keepdim=True) + 1e-8)

    return sparse_gates, top_k_idx


class MoELayer(nn.Module):
  def __init__(self, in_dim, hidden_dim, out_dim, n_experts, top_k):
    super().__init__()
    self.n_experts = n_experts
    self.top_k = top_k
    self.gate = GatingNetwork(in_dim, n_experts)
    self.experts = nn.ModuleList([
        Expert(in_dim, hidden_dim, out_dim) for _ in range(n_experts)
    ])

  def forward(self, x):
    B = x.shape[0]
    sparse_gates, top_k_idx = self.gate(x, self.top_k)

    #every expert on full scale
    expert_outputs = torch.stack([expert(x) for expert in self.experts], dim=1)

    #weighted sum
    out = (expert_outputs * sparse_gates.unsqueeze(-1)).sum(dim=1)

    #auxillary load balancing loss

    tokens_per_expert = (sparse_gates > 0).float().mean(dim=0)
    mean_gate_per_expert = sparse_gates.mean(dim=0)
    lb_loss = (tokens_per_expert * mean_gate_per_expert).sum() * self.n_experts

    return out, lb_loss, sparse_gates #gates for plots


class MoEClassifier(nn.Module):
  def __init__(self, in_dim, hidden_dim, n_classes, n_experts, top_k):
    super().__init__()
    self.moe = MoELayer(in_dim, hidden_dim, hidden_dim, n_experts, top_k)
    self.head = nn.Linear(hidden_dim, n_classes)

  def forward(self, x):
    features, lb_loss, gates = self.moe(x)
    logits = self.head(features)

    return logits, lb_loss, gates

model = MoEClassifier(in_dim, hidden_dim, n_classes, n_experts, top_k)
optimizer = torch.optim.Adam(model.parameters(), lr=lr)


print("starting training \n")

for epoch in range(epochs):
  model.train()
  total_loss, total_lb = 0, 0
  for x_batch, y_batch in loader:

    logits, lb_loss, _ = model(x_batch)
    loss = F.cross_entropy(logits, y_batch) + load_balancing_coeff*lb_loss

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    total_loss += loss.item()
    total_lb += lb_loss.item()

  if(epoch + 1) % 5 == 0:
    avg_loss = total_loss/len(loader)
    avg_lb = total_lb/len(loader)
    print(f"Epoch {epoch+1:3d}/{epochs} | "
          f"Loss: {avg_loss:.4f} | "
          f"LB: {avg_lb:.4f} | ")

model.eval()

all_gates, all_labels = [], []
with torch.no_grad():
  for x_batch, y_batch in loader:
    _, _, gates = model(x_batch)
    all_gates.append(gates)
    all_labels.append(y_batch)

all_gates = torch.cat(all_gates)
all_labels = torch.cat(all_labels)


heatmap = np.zeros((n_experts, n_classes))
for digit in range(n_classes):
    mask = all_labels == digit
    heatmap[:, digit] = all_gates[mask].mean(dim=0).numpy()


fig, axes = plt.subplots(1, 2, figsize=(16, 5))

# ── Plot 1: Heatmap with annotations ─────────────────────────
ax = axes[0]
sns.heatmap(
    heatmap,
    annot=True, fmt=".2f",          # show values in each cell
    cmap="Blues",
    xticklabels=range(10),
    yticklabels=[f"Expert {i}" for i in range(n_experts)],
    linewidths=0.5,                 # grid lines between cells
    ax=ax,
    vmin=0, vmax=1
)
ax.set_title("Avg gate weight per expert per digit", fontsize=13)
ax.set_xlabel("Digit"); ax.set_ylabel("Expert")

# ── Plot 2: Dominant expert per digit (cleaner story) ────────
ax = axes[1]
dominant = heatmap.argmax(axis=0)      # which expert wins each digit
colors = ["#E74C3C","#3498DB","#2ECC71","#F39C12"]
bars = ax.bar(range(10), [heatmap[dominant[d], d] for d in range(10)],
              color=[colors[dominant[d]] for d in range(10)],
              edgecolor="white", linewidth=1.2)

ax.set_xticks(range(10))
ax.set_xlabel("Digit"); ax.set_ylabel("Gate weight of dominant expert")
ax.set_title("Dominant expert per digit", fontsize=13)
ax.set_ylim(0, 1)

# Legend
import matplotlib.patches as mpatches
ax.legend(handles=[mpatches.Patch(color=colors[i], label=f"Expert {i}")
                   for i in range(n_experts)], loc="lower right")

# Annotate which expert owns each bar
for d in range(10):
    ax.text(d, heatmap[dominant[d], d] + 0.02,
            f"E{dominant[d]}", ha="center", fontsize=9)

plt.tight_layout()
plt.show()

